### ISSUE TITLE
Removing the observer is not necessary

### ISSUE THREAD

**Issue by inket** [zenangst/Vaccine#1]
Hi!

According to the documentation for `NotificationCenter.removeObserver`:

> If your app targets iOS 9.0 and later or macOS 10.11 and later, you don't need to unregister an observer in its dealloc method.

Since this framework's deployment target is iOS 9.2 & macOS 10.11, I believe there is no need to remove observers as `NotificationCenter` is only holding weak references to them.

Removing the need to call `Injection.remove(self)` in `deinit` should make it easier for the user.

**Comment by zenangst** [comment]
@inket hey mate. Oh... I didn't know that! That is pretty fantastic, I've only continued to do it out of habit. Thanks for bringing it to my attention :) I'll make some PR's to fix the issue.

**Comment by zenangst** [comment]
@inket 

![687474703a2f2f6d65646961302e67697068792e636f6d2f6d656469612f67655977746f644239416949302f67697068792e676966](https://user-images.githubusercontent.com/57446/40642387-4746f33c-631d-11e8-8820-046b53cf3e17.gif)
