### ISSUE TITLE
Setup instructions for Example fail to build

### ISSUE THREAD

**Issue by placrosse** [zenangst/Vaccine#20]
Following the setup instructions exactly, upon starting Xcode and opening VaccineDemo.xcworkspace:

Swift Compiler Error (2 issues)

/Users/paul/dev/Vaccine/Example/VaccineDemo/VaccineDemo/Sources/DataSources/ListDataSource.swift:15:38: Incorrect argument label in call (have '_:notification:', expected '_:in:')

/Users/paul/dev/Vaccine/Example/VaccineDemo/VaccineDemo/Sources/DataSources/DetailDataSource.swift:15:38: Incorrect argument label in call (have '_:notification:', expected '_:in:')

Xcode auto-fix corrects by changing to "in"

**Comment by zenangst** [comment]
Hey @placrosse, thanks for bringing this to my attention, I've made a PR to fix the issue now #21
