### ISSUE TITLE
Using in a MacOs Project

### ISSUE THREAD

**Issue by yanshiyason** [zenangst/Vaccine#44]
Hi there,

I tried running Vaccine with a MacOS and got the following exception when building:

```
~/../Pods/Vaccine/Source/Shared/CollectionView+Extensions.swift:13:25: Use of unresolved identifier 'UICollectionView'
```

```swift
Swizzling.swizzle(UICollectionView.self, // <----- Use of unresolved identifier 'UICollectionView'
                        originalSelector: originalSelector,
                        swizzledSelector: swizzledSelector)
```

At the top of the file, there is a compiler directive like this:
```swift
#if os(macOS)
import Cocoa
#else
import UIKit
#
```

But UICollectionView is only part of UIKit.

It seems like `CollectionView` is aliased to be `NSCollectionView` on mac and `UICollectionView` on ios. Would it make sense to use `CollectionView.self` here?

**Comment by yanshiyason** [comment]
Ahh! This seems to have been fixed [here](https://github.com/zenangst/Vaccine/commit/3810be63f349ea3384c48f111a812ee07837a30d)! Great!

**Comment by zenangst** [comment]
Seems like you solved it :)
Were you running an older version of Vaccine?

**Comment by yanshiyason** [comment]
That’s right! I didn’t specify the version in my Podfile and it ended up
using an early version.

Thank you for response!

**Comment by zenangst** [comment]
@yanshiyason awesome, have fun developing at lightning speed :)
