### ISSUE TITLE
Injection always says it is already loaded

### ISSUE THREAD

**Issue by eduardbosch** [zenangst/Vaccine#54]
Hi,

I'm trying this library, but when I load it, it always says that the injection in already loaded.

The problem is that my main bundle path is like this:
`/users/username/library/developer/coresimulator/devices/****/data/containers/bundle/application/****/appname.app`
and this line is always false: https://github.com/zenangst/Vaccine/blob/b529121ab3034c4156e023e20f08f3e473050feb/Source/Shared/Injection.swift#L89

If I remove this check, everything goes well.

Is this the intended result?

Many thanks

Environment:
Mojave 10.14.3 (18D109)
Xcode 10.1 (10B61)

**Comment by zenangst** [comment]
Hey @eduardbosch, that check was more intended for macOS but I think I'll go ahead and remove it as it is causing issues for people. Or even better, would you mind making a PR to remove it and I'll review it? :)

**Comment by eduardbosch** [comment]
Of course, I already had it on a fork 🙂

Here it is the PR https://github.com/zenangst/Vaccine/pull/55
